version : '3.8'

services:
  discount-postgres:
    image: postgres
    container_name: discount-postgres
    read_only: true
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discountDb
    expose:
      - "5433"
    ports:
      - "5433:5433"

    tmpfs:
      - /tmp
      - /run
      - /run/postgresql

    volumes:
      - discount-volume:/var/lib/postgresql/data
    command: -p 5433

volumes:
  discount-volume: